### ISSUE TITLE
请问下大佬是在什么设备上测试的

### ISSUE THREAD

**Issue by sagitn** [Xposed-Modules-Repo/com.zhufucdev.motion_emulator#1]
安卓9的小米6和安卓10的一加7p，magisk版本25.2，lsp1.8.5，只要激活模块就会无限软重启，

**Comment by zhufucdev** [comment]
s10，k30

暂时就这两个

~~不如把你手机寄给我~~

**Comment by GuXianWN** [comment]
> 

我也是无限重启，需要填token自己编译吗

**Comment by zhufucdev** [comment]
> > 
> 
> 我也是无限重启，需要填token自己编译吗

不认为这两件事有关

**Comment by zhufucdev** [comment]
我猜hook整个系统不是个好主意，建议给系统留个干净的环境

**Comment by fanshu-520** [comment]
原来无限重启的不只是我一个
