### ISSUE TITLE
分辨率异常

### ISSUE THREAD

**Issue by jaydon-zhuang** [Xposed-Modules-Repo/com.zhufucdev.motion_emulator#2]
屏幕分辨率，似乎有问题，停止的按钮跟我手机的虚拟按钮重叠了，无法按停止键。
小米10pro  miui13  安卓12
![Screenshot_2022-12-01-13-33-12-777_com zhufucdev motion_emulator](https://user-images.githubusercontent.com/85752999/204976309-0f33ac96-c6cb-4b5d-b50e-ad5d4bbb2bd3.jpg)

**Comment by jaydon-zhuang** [comment]
屏幕分辨率，似乎有问题，停止的按钮跟我手机的虚拟按钮重叠了，无法按停止键。
小米10pro  miui13  安卓12

**Comment by zhufucdev** [comment]
~使用手势导航即可~
