### ISSUE TITLE
一直显示“正在等待模拟，等待其他应用响应”，且gps无法模拟

### ISSUE THREAD

**Issue by THERentropy** [Xposed-Modules-Repo/com.zhufucdev.motion_emulator#3]
模块作用已勾选需要模拟的应用，且未勾选系统框架。
app：运动世界校园

**Comment by DineshValor** [comment]
Is it working with Lsposed module?

**Comment by DineshValor** [comment]
System framework need to hook in both Motion Emulator Xposed module?
